name: CI
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Setup Node
      uses: actions/setup-node@v1
      with:
        node-version: 14.4
    - name: Setup clang and GL
      run: |
        sudo add-apt-repository 'deb http://apt.llvm.org/bionic/ llvm-toolchain-bionic-10 main'
        sudo apt update
        sudo apt install clang-10 mesa-common-dev
    - name: Versions
      run: |
        node -v
        npm -v
        clang-10 --version
        make -v
    - uses: actions/checkout@v2
    - name: Setup .env
      run: |
        touch $GITHUB_WORKSPACE/.env
        echo "CLANG_BIN=clang-10" >> $GITHUB_WORKSPACE/.env
        echo "CLANG_TIDY_BIN=clang-tidy-10" >> $GITHUB_WORKSPACE/.env
    - name: Build
      run: |
        make setup
        make
