name: CI
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
jobs:
  ubuntu-build:
    runs-on: ubuntu-latest
    env:
      CLANG_BIN: clang-10
      CLANG_TIDY_BIN: clang-tidy-10
    name: Ubuntu Build
    steps:
    - name: Setup node.js
      uses: actions/setup-node@v1
      with:
        node-version: 14.4
    - name: Setup clang
      run: |
        sudo add-apt-repository 'deb http://apt.llvm.org/bionic/ llvm-toolchain-bionic-10 main'
        sudo apt update
        sudo apt install clang-10 clang-tidy-10
    - name: Setup graphical drivers
      run: |
        sudo apt install mesa-common-dev libxrandr-dev libxinerama-dev libxcursor-dev libxi-dev
    - name: Print versions
      run: |
        echo "Node:"
        node -v
        echo ""
        echo "npm:"
        npm -v
        echo ""
        echo "clang:"
        $(CLANG_BIN) --version
        echo ""
        echo "clang-tidy:"
        $(CLANG_TIDY_BIN) --version
        echo ""
        echo "make:"
        make -v
        echo ""
    - uses: actions/checkout@v2
    - name: Setup
      run: make setup
    - name: Build
      run: |
        make
        ls -al build
  macos-build:
    runs-on: macos-latest
    env:
      CLANG_BIN: clang
      CLANG_NO_TIDY: true
    name: MacOS Build
    steps:
    - name: Setup node.js
      uses: actions/setup-node@v1
      with:
        node-version: 14.4
    - name: Print Versions
      run: |
        echo "Node:"
        node -v
        echo ""
        echo "npm:"
        npm -v
        echo ""
        echo "clang:"
        $CLANG_BIN --version
        echo ""
        echo "make:"
        make -v
        echo ""
    - uses: actions/checkout@v2
    - name: Setup
      run: make setup
    - name: Build
      run: |
        make
        ls -al build
