name: CI
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Setup Node
      uses: actions/setup-node@v1
      with:
        node-version: 14.4
    - name: Setup clang
      run: |
        sudo add-apt-repository 'deb http://apt.llvm.org/bionic/ llvm-toolchain-bionic-10 main'
        sudo apt update
        sudo apt install clang-10
    - name: Versions
      run: |
        node -v
        npm -v
        clang --version
        make -v
    - uses: actions/checkout@v2
    - name: Build
      run: |
        make setup
        make
